controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_joint
      - bicep_joint
      - forearm_joint
      - wrist_joint
      - wrist2_joint
      - wrist3_joint
  - name: fake_gripper_controller
    joints:
      - end_effector_joint